### ISSUE TITLE
ModuleNotFoundError when starting outside of a container

### ISSUE THREAD

**Issue by zmc** [ceph/teuthology-api#18]
This looks related to #7.

When we deploy in production I'm not sure if we'll be able to use containers, at least if we want the `kill` endpoint to work. While trying to start up from a virtualenv, I get:

```
$ gunicorn -c gunicorn_config.py main:app
[2023-09-06 20:43:29 +0000] [710527] [INFO] Starting gunicorn 21.2.0
[2023-09-06 20:43:29 +0000] [710527] [INFO] Listening at: http://0.0.0.0:8082 (710527)
[2023-09-06 20:43:29 +0000] [710527] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-09-06 20:43:29 +0000] [710529] [INFO] Booting worker with pid: 710529
[2023-09-06 20:43:29 +0000] [710529] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/zack/teuthology-api/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/zack/teuthology-api/venv/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/zack/teuthology-api/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/zack/teuthology-api/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/zack/teuthology-api/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/zack/teuthology-api/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/zack/teuthology-api/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/zack/teuthology-api/venv/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2023-09-06 20:43:29 +0000] [710529] [INFO] Worker exiting (pid: 710529)
[2023-09-06 20:43:29 +0000] [710527] [ERROR] Worker (pid:710529) exited with code 3
[2023-09-06 20:43:29 +0000] [710527] [ERROR] Shutting down: Master
[2023-09-06 20:43:29 +0000] [710527] [ERROR] Reason: Worker failed to boot.
```

**Comment by VallariAg** [comment]
@zmc 
This error goes away when you `cd src/` and then run `gunicorn -c ../gunicorn_config.py main:app`. We are doing the same in Dockerfile.
